version: '3'

services:
  flask:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    command: ["/usr/src/boot_flask.sh"]
    volumes:
      - ./:/usr/src
    ports:
      - "5000:5000"
